#vich_uploader:
    #db_driver: orm
     

    #mappings:
        #products:
            #uri_prefix: /images/civilisations
            #upload_destination: '%kernel.project_dir%/public/images/civilisations'
            #namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


vich_uploader:
    db_driver: orm
    storage: file_system        
    mappings:
        civilisation_images:
            uri_prefix: /images/civilisations
            upload_destination: '%kernel.project_dir%/public/images/civilisations'
            namer: Vich\UploaderBundle\Naming\HashNamer
        programe_images:
            uri_prefix: /images/programes
            upload_destination: '%kernel.project_dir%/public/images/programes'
            namer: Vich\UploaderBundle\Naming\HashNamer

        



