<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hotel extends \App\Entity\Hotel implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'features' => [parent::class, 'features', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'reservationHotels' => [parent::class, 'reservationHotels', null],
        "\0".parent::class."\0".'resrvations' => [parent::class, 'resrvations', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        'features' => [parent::class, 'features', null],
        'id' => [parent::class, 'id', null],
        'reservationHotels' => [parent::class, 'reservationHotels', null],
        'resrvations' => [parent::class, 'resrvations', null],
        'titre' => [parent::class, 'titre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
