<?php

namespace Container2RwPOji;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationHotel2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rv0xkic.App\Entity\ReservationHotel' shared service.
     *
     * @return \App\Entity\ReservationHotel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rv0xkic": it needs an instance of "App\\Entity\\ReservationHotel" but this type has been excluded in "config/services.yaml".');
    }
}
