<?php

namespace ContainerYRokx5z;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JfBQivKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jfBQivK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jfBQivK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repoHotel' => ['privates', 'App\\Repository\\ReservationHotelRepository', 'getReservationHotelRepositoryService', true],
            'repoProgramme' => ['privates', 'App\\Repository\\ReservationProgrammeRepository', 'getReservationProgrammeRepositoryService', true],
            'repoRestaurant' => ['privates', 'App\\Repository\\ReservationRestaurantRepository', 'getReservationRestaurantRepositoryService', true],
            'repoUser' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'repoHotel' => 'App\\Repository\\ReservationHotelRepository',
            'repoProgramme' => 'App\\Repository\\ReservationProgrammeRepository',
            'repoRestaurant' => 'App\\Repository\\ReservationRestaurantRepository',
            'repoUser' => 'App\\Repository\\UserRepository',
        ]);
    }
}
