<?php

namespace ContainerYRokx5z;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgrameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Dt0iHVJ.App\Entity\Programe' shared service.
     *
     * @return \App\Entity\Programe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Dt0iHVJ": it needs an instance of "App\\Entity\\Programe" but this type has been excluded in "config/services.yaml".');
    }
}
