<?php

namespace ContainerYRokx5z;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationRestaurantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F2x5AtQ.App\Entity\ReservationRestaurant' shared service.
     *
     * @return \App\Entity\ReservationRestaurant
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.F2x5AtQ": it needs an instance of "App\\Entity\\ReservationRestaurant" but this type has been excluded in "config/services.yaml".');
    }
}
