<?php

namespace ContainerIcSAvei;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QVDZ2RpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qVDZ2Rp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qVDZ2Rp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'civilisationRepository' => ['privates', 'App\\Repository\\CivilisationRepository', 'getCivilisationRepositoryService', true],
        ], [
            'civilisationRepository' => 'App\\Repository\\CivilisationRepository',
        ]);
    }
}
