<?php

namespace ContainerDiv0sIP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C5S8a7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c5_s8a7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c5_s8a7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationHotelRepository' => ['privates', 'App\\Repository\\ReservationHotelRepository', 'getReservationHotelRepositoryService', true],
        ], [
            'reservationHotelRepository' => 'App\\Repository\\ReservationHotelRepository',
        ]);
    }
}
