<?php

namespace ContainerHNrfT2e;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_UgS49nMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.UgS49nM' shared service.
     *
     * @return \App\Controller\ProgrameRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ReservationProgrammeController::new()": the $repo argument is type-hinted with the non-existent class or interface: "App\\Controller\\ProgrameRepository". Did you forget to add a use statement?');
    }
}
