<?php

namespace ContainerHNrfT2e;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rv0xkicService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rv0xkic' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rv0xkic'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservationHotel' => ['privates', '.errored..service_locator.rv0xkic.App\\Entity\\ReservationHotel', NULL, 'Cannot autowire service ".service_locator.rv0xkic": it needs an instance of "App\\Entity\\ReservationHotel" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'reservationHotel' => 'App\\Entity\\ReservationHotel',
        ]);
    }
}
