<?php

namespace ContainerUhFGbvd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EvaCXXuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.evaCXXu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.evaCXXu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hotelRepository' => ['privates', '.errored.w7hkBmh', NULL, 'Cannot determine controller argument for "App\\Controller\\HotelController::index()": the $hotelRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\HotelRepository".'],
        ], [
            'hotelRepository' => '?',
        ]);
    }
}
