<?php

namespace ContainerExdWeA1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCivilisationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6WpbVPW.App\Entity\Civilisation' shared service.
     *
     * @return \App\Entity\Civilisation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6WpbVPW": it needs an instance of "App\\Entity\\Civilisation" but this type has been excluded in "config/services.yaml".');
    }
}
