<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJnrlPmj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJnrlPmj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJnrlPmj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJnrlPmj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJnrlPmj\App_KernelDevDebugContainer([
    'container.build_hash' => 'JnrlPmj',
    'container.build_id' => 'df78bfd4',
    'container.build_time' => 1709472104,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJnrlPmj');
