<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWALyKe2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWALyKe2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWALyKe2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWALyKe2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWALyKe2\App_KernelDevDebugContainer([
    'container.build_hash' => 'WALyKe2',
    'container.build_id' => '63d50adc',
    'container.build_time' => 1709468365,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWALyKe2');
