<?php

namespace ContainerMF6zfRd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9JmOAa6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9JmOAa6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9JmOAa6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'reservationRestaurantRepository' => ['privates', 'App\\Repository\\ReservationRestaurantRepository', 'getReservationRestaurantRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\UserRepository',
            'reservationRestaurantRepository' => 'App\\Repository\\ReservationRestaurantRepository',
        ]);
    }
}
