<?php

namespace ContainerBNQsK2e;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationProgramme3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F6QSc9e.App\Entity\ReservationProgramme' shared service.
     *
     * @return \App\Entity\ReservationProgramme
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.F6QSc9e": it needs an instance of "App\\Entity\\ReservationProgramme" but this type has been excluded in "config/services.yaml".');
    }
}
